### ISSUE TITLE
Resolve self-hosted SSL + OkHttp 3.9.1+ issue

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#919] opened 2018-10-09 13:02 UTC
It looks like OkHttp `3.9.1` or later breaks support for self-hosted SSL sites (at least, it does for our shared test site). We're currently on `3.9.0` for this reason - if/when we want to update `OkHttp`, we'll need to understand and resolve the issue.

See https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/918 for some background.

**Comment by jtreanor** [comment] 2019-01-21 18:12
This issue is now manifesting in WPAndroid (https://github.com/wordpress-mobile/WordPress-Android/issues/9032) due Gradle resolving to `3.11.0`.

**Comment by jtreanor** [comment] 2019-01-22 13:49
Update: I have merged https://github.com/wordpress-mobile/WordPress-Android/pull/9040 to remove the immediate impact on WPAndroid.

The cause may be related to square/okhttp#4053.

**Closed** 2020-11-10 16:10 UTC
Labels: Core
