### ISSUE TITLE
ClassCastException: java.lang.String cannot be cast to java.lang.Double in postResponseToPostModel

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1574] opened 2020-05-06 10:01 UTC
Although we only have 2 instances of this crash, it started happening in the latest beta version that's released 2 days ago. It might point to a change in the API, so I thought it'd be best to report it early.

**Sentry Url**: https://sentry.io/share/issue/928af6d2ee6349b795c89ccdaecbc43f/
**User Count**: 1
**Count**: 2
**First Release**: org.wordpress.android-14.8-rc-1
**First Seen**: 2020-05-06T06:59:57Z
**Last Seen**: 2020-05-06T07:00:01Z
**24 Hours**: 2
**30 Days**: 2

```
ClassCastException: java.lang.String cannot be cast to java.lang.Double
     at org.wordpress.android.fluxc.network.rest.wpcom.post.PostRestClient.postResponseToPostModel(PostRestClient.java:440)
     at org.wordpress.android.fluxc.network.rest.wpcom.post.PostRestClient.access$000(PostRestClient.java:67)
     at org.wordpress.android.fluxc.network.rest.wpcom.post.PostRestClient$9.onResponse(PostRestClient.java:244)
     at org.wordpress.android.fluxc.network.rest.wpcom.post.PostRestClient$9.onResponse(PostRestClient.java:241)
     at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:53)
     at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
     at android.os.Handler.handleCallback(Handler.java:883)
     at android.os.Handler.dispatchMessage(Handler.java:100)
     at android.os.Looper.loop(Looper.java:214)
     at android.app.ActivityThread.main(ActivityThread.java:7356)
...
(3 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment] 2020-05-08 20:30
@malinajirka Could you take a quick peek at this?

**Comment by malinajirka** [comment] 2020-05-11 09:25
Sure thing;)!

I've looked into the issue. 
Version `14.8-rc-1` of WPAndroid uses FluxC `1.6.11`. The line 440 in FluxC `1.6.11` contains the following code `List<String> tagNames = new ArrayList<>();` so it can't crash with the `java.lang.String cannot be cast to java.lang.Double` exception.

However, I noticed that the current FluxC's `develop` contains changes from FluxC `7f24d167a8141ae9246ac6946483cf2376bcbaba` - https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/7f24d167a8141ae9246ac6946483cf2376bcbaba/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostRestClient.java#L440. 

So I came to a conclusion that this issue was recorded by one of our developers - it's not actually merged in 14.8-rc-1. It seems the developer was using `vanilla` build and therefore the `versionName` was set to `14.8-rc-1`. @oguzkocer I'm wondering if we should update WPAndroid-build.gradle so it doesn't use real version names during development. Wdyt?

**Comment by oguzkocer** [comment] 2020-05-13 20:16
@malinajirka That makes sense - let me think about how best we can achieve this. Having said that, was this issue still useful? We sometimes have crashes during development for unrelated things and can't create an issue because we are not sure what actually caused it. Creating an issue that's not shipped in a beta should be a rare case, so if there is some value to it, maybe we shouldn't put in the extra effort to disable it?

**Comment by malinajirka** [comment] 2020-05-14 07:19
I'm sorry, I wasn't suggesting we should disable it. It'd be just nice to see the correct version name or at least some indication that this was recorded during development. Because, I was looking for the issue in the `14.8-rc-1` branch, but it wasn't there. It took me some time to realize, what's going on and knowing that `List<String> tagNames = new ArrayList<>();` can't crash with this type of exception helped a lot. If the exception was a bit different and the line contained a different code I could have wasted a day trying to figure out what the issue is.

I think the adjustment could be as simple as changing [this line](https://github.com/wordpress-mobile/WordPress-Android/blob/0b71284d12957968d49c3a06bdba8d07e240f252/WordPress/build.gradle#L88) on developers builds to 
1. Ideally a commit hash, something like "a32787a-dev"
or
2. "14.8-rc-1-dev"

Wdyt?

**Comment by malinajirka** [comment] 2020-05-14 07:25
@ashiagr It seems this crash was recorded while working on https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1577. Could you please verify that the crash has been fixed in that PR, before it gets merged. Thanks!

**Comment by ashiagr** [comment] 2020-05-14 07:30
Yes, it is fixed in this commit 6ad8c65.

**Comment by malinajirka** [comment] 2020-05-14 07:32
@oguzkocer I'm closing this issue and the Sentry issue. We can continue with the discussion on slack.

**Closed by malinajirka** 2020-05-14 07:32 UTC
Labels: [Type] Crash

**Comment by oguzkocer** [comment] 2020-05-14 16:42
> I think the adjustment could be as simple as changing [this line](https://github.com/wordpress-mobile/WordPress-Android/blob/0b71284d12957968d49c3a06bdba8d07e240f252/WordPress/build.gradle#L88) on developers' builds

In order to change that line we'll need to update our release toolkit scripts. Changing [this line](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/CrashLoggingUtils.kt#L23) instead would probably be enough, but there are 2 recorded versions in Sentry if I am not mistaken, so I'll need to check.

This might all be a moot point though, because before we enable crash logging, we check if we should [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/CrashLoggingUtils.kt#L30) and return `false` if it's a `DEBUG` build [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/CrashLoggingUtils.kt#L12-L14). So, this crash seems to have happened on a non-`DEBUG` build. That's not a common way we develop our apps, so I don't think any work around this is worth the effort.

**Comment by malinajirka** [comment] 2020-05-15 07:16
👍 I agree, let's not take any actions at the moment and wait if it happens again.
