### ISSUE TITLE
Jetpack - Image size larger than site's max_upload_filesize error message workaround

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-FluxC-Android#402] opened 2017-04-03 10:16 UTC
When you try to upload an image through the wp.com API to a Jetpack site and it's too large (larger than the site's `max_upload_filesize`), it will fail with an error that doesn't seem relevant:

`The corresponding HMAC for this file does not match`

<img src="https://cloud.githubusercontent.com/assets/518232/24604891/f6682316-1866-11e7-81e3-1d8a8049fe92.png" width="270" alt="screenshot_20170324-162026">

Ref: https://github.com/Automattic/jetpack/issues/3400

We should try to capture this error here in the library, give a specific error type, and propagate it to the client.

**Comment by designsimply** [comment] 2019-10-30 23:33
@daniloercoli I tested uploading images and videos on a site set with `upload_max_filesize = 1M` today and found that the image was too big the error message was good:

> Files exceeds the maximum upload size for …

But when the video was too big the error message was very generic:

> We couldn't complete this action.

See https://github.com/Automattic/jetpack/issues/3400#issuecomment-548155082.

**Comment by designsimply** [comment] 2020-11-19 05:45
I tried re-testing this today and was unable to reproduce the problem using the following steps:

1. Set up a Jetpack site and use php.ini to set `upload_max_filesize = 1M`.
1. In the app, go to My Site > Account > App Settings and enable the "Optimize Images" setting.
1. Go to My Sites > Media.
1. Try to upload an image larger than 1MB.

**Result:** when I try to upload an image larger than the max upload file size set by the server I don't see an HMAC-related error message but I do see an expected error letting me know "File exceeds the maximum upload filesize" and when I try to upload an image that's an allowed size smaller than the max filesize setting on the server it works normally. ([30s](https://cloudup.com/ce70v7TeyKZ))

upload_max_filesize|optimize setting is on|sample file is 2MB|upload fails with appropriate error
---|---|---|---
![Screenshot_20201118-213216](https://user-images.githubusercontent.com/1119271/99626586-61cde600-29e7-11eb-914e-35f3f3b8476f.png)|![Screenshot_20201118-212153](https://user-images.githubusercontent.com/1119271/99626590-6397a980-29e7-11eb-8a29-a8e937f48567.png)|![Screenshot_20201118-213024](https://user-images.githubusercontent.com/1119271/99626587-62667c80-29e7-11eb-87f6-01cfaaf7430a.png)|![Screenshot_20201118-212856](https://user-images.githubusercontent.com/1119271/99626588-62ff1300-29e7-11eb-853f-2b2d4a32bd44.png)

<sup>Tested with WPAndroid 16.2-rc-1 on Pixel 3 Android 11.</sup>

Closing because I have been unable to reproduce the problem in testing and because we've made several recent changes to the media picker to improve it. cc @planarvoid

**Closed by designsimply** 2020-11-19 05:45 UTC
Labels: Error Management, [Store] Media
