### ISSUE TITLE
Crash when adding a self hosted site 

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#284] opened 2017-01-20 08:53 UTC
Originally from [here](https://github.com/wordpress-mobile/WordPress-Android/pull/4455#issuecomment-242238265). In the Example App:

* Log into .com account with a Jetpack site
* Log into that Jetpack site as self-hosted
* Site -> Fetch All sites
* 💥 

```
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: SiteModel.SITE_ID, SiteModel.URL (code 2067)
    at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732)
    at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
    at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
    at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)
    at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
    at com.yarolegovich.wellsql.UpdateQuery.execute(UpdateQuery.java:79)
    at org.wordpress.android.fluxc.persistence.SiteSqlUtils.insertOrUpdateSite(SiteSqlUtils.java:87)
    at org.wordpress.android.fluxc.store.SiteStore.updateSite(SiteStore.java:566)
    at org.wordpress.android.fluxc.store.SiteStore.onAction(SiteStore.java:502)
    at java.lang.reflect.Method.invoke(Native Method)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479) 
    at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 
```

**Comment by maxme** [comment] 2017-01-20 08:55
Not sure how to handle that since the site_id only comes from the FETCH_SITE, so the site is already added to the DB (I'm not sure if we should remove it). We can maybe try to check if the site is already in before inserting.

**Comment by aforcier** [comment] 2017-01-24 19:21
I think this is pretty much a duplicate of https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/58. Or, at least, #285 will close both of these issues.

**Closed** 2017-01-25 13:30 UTC
